### ISSUE TITLE
Allow easier way to set  JUPYTERLAB_DIR or conda env

### ISSUE THREAD

**Issue by fzimmermann89** [slac-lcls/jhub2#1]
Hi,

it would be nice if there was an easy way to set  JUPYTERLAB_DIR or the conda environment the jupyterlab will start in. This would allow installation of labextensions such as the git extension or ipywidgets for interactive plotting.

The current implenentation makes sure not to run a .bashrc before starting the jupyterlab which makes it difficult to make changes to the environment (still possible, but much more ugly than it could be).
A nicer way could be to try to source a .jhubrc if it exists at https://github.com/slac-lcls/jhub2/blob/master/sshspawner.py#L64.

Thanks,
Felix

**Comment by weninc** [comment]
Yes I agree that jupyter extensions are important, but I think you can install them without having to change out the jupyterlab executable.
The following should work:
source /reg/g/psdm/sw/jupyterhub/miniconda3/etc/profile.d/conda.sh 
conda activate jhub

- list the extensions
jupyter labextension list
- or 
jupyter labextension  install my-extension

**Comment by fzimmermann89** [comment]
Thanks for the reply!

Unfortunalty this won't work as the labextensions will be saved in a common folder which I cannot write to:

```
pslogin01 ➜   source /reg/g/psdm/sw/jupyterhub/miniconda3/etc/profile.d/conda.sh
pslogin01➜  conda activate jhub
(jhub) pslogin01➜   jupyter labextension install @jupyter-widgets/jupyterlab-manager
[....]
Node v8.12.0

> /reg/g/psdm/sw/jupyterhub/miniconda3/envs/jhub/bin/npm pack @jupyter-widgets/jupyterlab-

Errored, use --debug for full output:
PermissionError: [Errno 13] Permission denied: '/reg/g/psdm/sw/jupyterhub/miniconda3/envs/jhub/share/jupyter/lab/extensions/jupyter-widgets-jupyterlab-manager-0.38.1.tgz'
```
The only solutions I can think of are either
- Use a different environment for  jupyerlab (in my home) or
- Set JUPYTERLAB_DIR to be somewhere I can write to

I've a somewhat working solution for my usecase, but I'd like to have a more robust/semi-official way to do it..
